name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build package
        run: |
          echo "Build process for LanzarMAXP124D"
